name: QA Approval Required

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  check-qa-approval:
    runs-on: ubuntu-latest
    steps:
    - name: Check for QA Approval
      env:
        GITHUB_TOKEN: ${{ secrets.HL_AUTOMATION_GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        #!/bin/bash set +x
        # Fetch the list of reviews on the PR
        reviews=$(gh api repos/$REPO/pulls/$PR_NUMBER/reviews --paginate -q '.[] | select(.state=="APPROVED") | .user.login')
        # Check if any of the reviewers are in the QA team
        for reviewer in $reviews; do
          # Check if the reviewer is a member of the QA team
          if gh api orgs/HonorLock/teams/qa/memberships/$reviewer -q '.state' | grep active; then
            echo "PR has been approved by QA team member: $reviewer"
            exit 0
          fi
        done
        echo "No approvals from QA team members found."
        exit 1
        